//
// Created by Gilbert Gwizdala on 2019-07-30.
//

#ifndef TERRENRENDERING_TERRAINTESSELLATIONMANAGER_H
#define TERRENRENDERING_TERRAINTESSELLATIONMANAGER_H


class TerrainTessellationManager {

};


#endif //TERRENRENDERING_TERRAINTESSELLATIONMANAGER_H
